[platformio]
src_dir = .

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
board_build.flash_mode = dio
board_build.f_flash = 40000000L
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_extra_dirs = 
    /home/aliyofi/Arduino/libraries
